ast_ES:
  bridge:
    description: Munches estraes nes fasteres fora de les villes dibúxense apriesa y ensin mirar si crucen ríos o regatos. Alcuentra un llugar onde un mapeador escaeció partir una estrada y marcar una ponte, y faelo tu.
    title: Dibuxa una ponte
  stream:
    description: Los ríos del mundu tán nel mapa cuasi completamente, pero hai una cantidá de regatos grande enforma pa que tean toos. Alcuentra un regatu (non una canal) y ponlu nel mapa.
    title: Dibuxa un regatu
  postcode:
    description: En dellos paises, como Rusia o los EEXX, puedes buscar un códigu postal nuna base de datos disponible de mou públicu. N'otros puedes sabelo o deducilo de fontes indireutes, como la páxina web d'una tienda. Alcuentra'l códigu postal de cualquier edificiu que nun lu tenga, y ponlu nel mapa.
    title: Amiesta un códigu postal
  bench:
    description: ¿Alcuérdeste de cuando fuisti a un parque qu'había bancos? Tenta alcordate de los llugares, porque la siguiente xera ye amestar un bancu.
    title: Dibuxa un bancu
  turn_restriction:
    description: Alcuentra una torga de xiru que nun tea nel mapa en Mapillary o otra fonte compatible con OSM. Si quiés, escueyi una villa más pequeña. Pon la torga nel mapa.
    title: Amiesta una torga de xiru
  lit:
    description: De nueche les ciudaes tienen meyor aspeutu cuando les cais tán illuminaes. Amiesta ''lit=yes'' o ''lit=no'' en delles rúes, y llueu mírales en color [http://product.itoworld.com/map/69 nesti mapa].
    title: Pinta la lluz d'una rúa
  osmand:
    title: Usar OsmAnd
  improve_river:
    description: "Bona parte de los ríos yá tán nel mapa. El problema ye qu'esto ta fecho usando imaxes de satélite de baxa resolución. Agora puedes ameyoralo: llanza JOSM, seleiciona un ríu, prime «W» y ameyora la vía. Amiesta polo menos 10 nodos a un ''waterway=river''."
    title: Ameyorar un ríu
  josm:
    description: "Instala l'editor JOSM, si nun lo ficisti yá, y edita daqué con él. Recomendamos dibuxar dellos edificios:\n \nDescarga parte del mapa, añade una capa d'imaxe, prime «A» y fai click na esquina d'un edificiu. Darréu fai doble-click nuna esquina axacente corner, pa crear una llinia. Entós prime «X» y arrastra la llinia pa tresformala nun rectángulu. P'acabar, prime «Alt+A» p'añadir ''building=yes'', y xube'l cambiu."
    title: Fai una edición con JOSM
  fix:
    description: 'Los comentarios de los conxuntos de cambios son importantes. Pero güei ye más fácil pa ti: fai un cambiu y pon «fix» nel campu de comentariu de los cambios. Sólo eses trés lletres, nada más.'
    title: Una pequeña igua
  gomap:
    title: Go Map!!!
  giveway:
    description: Hai una etiqueta especial pa marcar el triángulu de la señal «dexe pasu» nel mapa. Ye [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dgive_way highway=give_way], naturalmente. Alcuentra esa señal, o usando Mapillary o de memoria, pon un nodiu na estrada que tien de dexar pasar, y marca esi nodiu cola etiqueta. Añade tamién una etiqueta priority_road a la estrada con preferencia.
    title: Dexe'l pasu
  note:
    description: Activa les notes nel sitiu web d'OSM y alcuentra una nota ensin resolver que puedas iguar. Marca la nota como resuelta.
    title: Resuelve una nota
  around_the_world:
    description: Vamos crear un conxuntu de cambios con un cuadru de llende xigante. Primero dibuxa daqué nel [https://www.openstreetmap.org/#map=5/-48.487/-69.895 Sur de Chile], Y llueu en [https://www.openstreetmap.org/#map=6/55.912/159.335 Kamchatka].
    title: Alredor del mundu en cinco minutos
  highway:
    description: De vezu esta ye la primera cosa que fai la xente al xunise a OpenStreetMap. Alcuentra una estrada cercaba que nun tea nel mapa y añádela.
    title: Pon una estrada nel mapa
  subway:
    description: Pa esto necesites conocer l'[https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping esquema de Tresporte Públicu v2]. Visita'l [https://osmz.ru/subways/ Validador de metro] y escueye una ciudá con un error nel metro. Tendría d'implicar tresformar una ruta de metro. Igua'l fallu (y puedes dexalo equí, o siguir llimpiando la rede).
    title: Igua un metro
  buildings:
    description: Dibuxa polo menos 20 edificios per ende. Abre'l to editor favoritu, navega a dalgún llugar poco mapeáu nuna fastera industrial o d'aldea, y dibuxa dellos edificios.
    title: Dibuxar venti edificios
  lanes:
    description: Alcuentra una estrada que nun tenga puesta la etiqueta ''lanes''. Busca unes bones imáxenes del área y amiesta'l númberu de carriles de la estrada.
    title: Cuenta los carriles
  streetcomplete:
    description: Si'l to teléfonu ye un iPhone, mala suerte. N'Android, instala l'aplicación [https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete StreetComplete] y fai delles xeres. Tardes sólo un segundu con cauna.
    title: Mapea con StreetComplete
  leaf_types:
    description: Poner nel mapa un árbol nun ye sólo poner un nodiu ''natural=tree''. Tienes d'especificar el tipu. Mira les páxines de la wiki de [https://wiki.openstreetmap.org/wiki/Key:leaf_type leaf_type] y [https://wiki.openstreetmap.org/wiki/Key:leaf_cycle leaf_cycle], y llueu amiesta 2 árboles cerca de casa o nun llugar que conozas bien usando eses etiquetes.
    title: Planta dos árboles
  waste_basket:
    description: "Cuando sales, pases cerca de milenta papeleres: cabo les tiendes, nes paraes d'autobús, nes entraes de cases... Alcuérdate d'una, y ponla nel mapa con ''amenity=waste_basket''."
    title: Papeleres
  tiger:
    description: '[https://wiki.openstreetmap.org/wiki/TIGER TIGER] ye un conxuntu de datos de dominiu públicu d''estraes de los EEXX. Importóse nel 2005, y la importación foi imperfeuta. Alcuentra una estrada con tiger:reviewed=no ya igua polo menos trés, poniendo una clas d''estrada correuta y desaniciando la etiqueta.'
    title: Igua un Tiger
  tracks:
    description: Una pista ye un camín que lleva a dalguna casería o ta nuna viesca. Márcase con [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack highway=track] y con ''tracktype=gradeN'' opcional, onde N ta ente 1 (meyor) y 5 (peor). Alcuentra un campu o una viesca y dibuxa 2-3 km de pista.
    title: Dibuxa delles pistes
  hot_task:
    description: 'Abre l''[https://tasks.hotosm.org/ Alministrador de Xeres de HOT] y escueye una xera activa al debalu. Ehí, escueye un rectángulu mariellu cualquiera y fai una convalidación. Comprueba cómo dibuxen los edificios los mapeadores nuevos, reflexona un poco, y corrixe lo necesario: enderecha muros, ameyora formes. Val con un par d''igües.'
    title: Igua un edificiu
  lamps:
    description: ¿Ta escuro fora? ¿Ves una rúa allumada por una farola? Tamos enforma seguros de qu'esa farola nun ta nel mapa. Amiesta polo menos dos [https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp highway=street_lamp]s.
    title: Llanta una farola
  coastline:
    description: Munches llinies costeres importáronse cuantayá dixitalizando dende semeyes de satélite de baxa resolución. Puedes ayudar a ameyorales definitivamente'n dellos llugares. Amiesta polo menos 10 nodios na llinia de costa.
    title: Ameyora una costa
  haiti:
    description: 'En 2010 hebo un terremotu catastróficu a 25 km al oeste de la capital d''Haití, Puertu Príncipe. Eso dio principiu al Equipu Humanitariu de Cartografía, gracies al que se fexo''l mapa de la capital a la perfección. Pero non nel restu del país: alcuentra un edificiu n''Haití que nun tea nel mapa y trázalu.'
    title: Visitar Haití
  railway:
    description: De vezu los ferrocarriles reciben menos atención que les estraes, ¡pero nun son menos importantes! Pon nel mapa una llinia de ferrocarril. Si nun atopes ónde, tenta amestar les víes d'apartaderu que falten nes estaciones.
    title: Dibuxa un ferrocarril
  turnlanes:
    description: Llei la descripción de [https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane turn:lanes], busca una interseición con carriles visibles na imaxe de fondu o en Mapillary y mapea toles carriles de xiru nos cuatro llaos de la interseición.
    title: Carriles de xiru
  farmland:
    description: Alcuentra una zona de cultivu o prau (tenta nel centru de los EEXX o nel Oeste de Rusia) y añádela al mapa con [https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarmland landuse=farmland].
    title: Pon nel mapa una tierra de llabor
  switch:
    description: Cuando s'amiesten dos víes de tren, fácenlo con un cambiu d'aguyes. Busca una estación y añade polo menos dos etiquetes [https://wiki.openstreetmap.org/wiki/Tag:railway%3Dswitch railway=switch] a los nodios onde se coneuten les víes.
    title: Fai un cambiu d'aguyes
  mapsme:
    description: MAPS.ME nun ye sólo un visor y navegador multiplataforma del mapa. Puedes editar el mapa con él. Simplemente pulsia nun puntu d'interés, o seleiciona «Añadir un llugar» nel menú. Tenta eso.
    title: Usa MAPS.ME
  sidewalk:
    description: Una cera ye un camín cabo una estrada. Pa un meyor enrutamientu de peatones, alcuentra una estrada ensin cera nel mapa, y dibuxa un camín a cada llau (comprobando con una imaxe) y amiesta una etiqueta ''footway=sidewalk''. Ci amiestes un pasu de peatones como camín, usa ''highway=footway + footway=crossing''.
    title: Amiesta una cera
  delete:
    description: Nun ye abegoso atopar daqué pa poner nel mapa, pero ¿puedes alcontrar daqué pa borrar? Borra 5 elementos (pero sólo si tán anticuaos o son redundantes).
    title: ¡Desaniciar!
